language: python

python:
  - '3.6'

install:
  - wget -q https://download.pytorch.org/libtorch/nightly/cpu/libtorch-shared-with-deps-latest.zip
  - unzip -q libtorch-shared-with-deps-latest.zip && rm libtorch-shared-with-deps-latest.zip
  - pip -q install torch_nightly torchvision -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
  - pip freeze

script:
  - python ./python/export_to_pt_model.py
  - ./example-app/build.sh
