language: python

python:
  - '3.6'

install:
  - wget https://download.pytorch.org/libtorch/nightly/cpu/libtorch-shared-with-deps-latest.zip
  - unzip libtorch-shared-with-deps-latest.zip && rm libtorch-shared-with-deps-latest.zip
  - pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
  - pip install torchvision

script:
  - python ./python/export_to_pt_model.py
  - ./example-app/build.sh
