language: python

python:
  - '3.6'

install:
  - wget -q https://download.pytorch.org/libtorch/nightly/cpu/libtorch-shared-with-deps-latest.zip
  - unzip -q libtorch-shared-with-deps-latest.zip && rm libtorch-shared-with-deps-latest.zip
  - pip -q install torch_nightly -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
  - pip install pillow
  - pip install torchvision --no-deps
  - pip freeze
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install gcc-5 g++-5
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5

script:
  - python ./python/export_to_pt_model.py
  - ./example-app/build.sh
